version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask-cicd-demo
  - source: /scripts/flaskapp.service
    destination: /etc/systemd/system/flaskapp.service
permissions:
  - object: /home/ec2-user/flask-cicd-demo
    owner: ec2-user
    group: ec2-user
  - object: /etc/systemd/system/flaskapp.service
    owner: root
    group: root
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root